extends SceneTree

func _init() -> void:
	var payload := parse_single_payload(OS.get_cmdline_args())
	if payload.has("__codex_error__"):
		return

	var raw_target_dir = require_key(payload, "target_dir")
	if raw_target_dir == null:
		return

	var target_dir := String(raw_target_dir)
	var project_name := String(payload.get("project_name", "New Godot Project"))
	var root_node_type := String(payload.get("root_node_type", "Node2D"))
	var folders: Array = payload.get("folders", ["scenes", "scripts", "assets"])
	var create_main_scene := bool(payload.get("create_main_scene", true))
	var main_scene_path := String(payload.get("main_scene_path", "scenes/Main.tscn"))

	var mkdir_error := DirAccess.make_dir_recursive_absolute(target_dir)
	if mkdir_error != OK and mkdir_error != ERR_ALREADY_EXISTS:
		fail("cannot create target directory: %s" % target_dir)
		return

	for folder in folders:
		var folder_name := String(folder).replace("\\", "/").trim_prefix("/").trim_suffix("/")
		if folder_name.is_empty():
			continue
		var folder_path := target_dir.path_join(folder_name)
		var folder_error := DirAccess.make_dir_recursive_absolute(folder_path)
		if folder_error != OK and folder_error != ERR_ALREADY_EXISTS:
			fail("cannot create folder: %s" % folder_path)
			return

	if create_main_scene:
		var scene_abs_path := target_dir.path_join(main_scene_path.replace("/", "\\"))
		var scene_parent := scene_abs_path.get_base_dir()
		var scene_dir_error := DirAccess.make_dir_recursive_absolute(scene_parent)
		if scene_dir_error != OK and scene_dir_error != ERR_ALREADY_EXISTS:
			fail("cannot create main scene directory: %s" % scene_parent)
			return
		var scene_file := FileAccess.open(scene_abs_path, FileAccess.WRITE)
		if scene_file == null:
			fail("cannot open main scene file: %s" % scene_abs_path)
			return
		scene_file.store_string("[gd_scene format=3]\n\n[node name=\"Main\" type=\"%s\"]\n" % root_node_type)
		scene_file.close()

	var project_file := FileAccess.open(target_dir.path_join("project.godot"), FileAccess.WRITE)
	if project_file == null:
		fail("cannot open project.godot")
		return

	var project_lines := [
		"; Engine configuration file.",
		"; Generated by tool_init_project.gd",
		"",
		"config_version=5",
		"",
		"[application]",
		"",
		"config/name=\"%s\"" % escape_ini_string(project_name),
		"config/features=PackedStringArray(\"4.6\")",
	]
	if create_main_scene:
		project_lines.append("run/main_scene=\"res://%s\"" % main_scene_path.replace("\\", "/"))
	project_lines.append("")

	project_file.store_string("\n".join(project_lines))
	project_file.close()

	print(target_dir.path_join("project.godot"))
	quit()

func parse_single_payload(args: PackedStringArray) -> Dictionary:
	var script_index := args.find("--script")
	if script_index == -1 or args.size() <= script_index + 2:
		fail("expected: --script <script> <json-payload>")
		return {"__codex_error__": true}
	var raw := String(args[script_index + 2])
	if raw.begins_with("@"):
		var payload_path := raw.trim_prefix("@")
		var payload_file := FileAccess.open(payload_path, FileAccess.READ)
		if payload_file == null:
			fail("cannot open payload file: %s" % payload_path)
			return {"__codex_error__": true}
		raw = payload_file.get_as_text()
		payload_file.close()
	var json := JSON.new()
	var error := json.parse(raw)
	if error != OK:
		fail("invalid json payload")
		return {"__codex_error__": true}
	var data = json.get_data()
	if typeof(data) != TYPE_DICTIONARY:
		fail("payload must be a dictionary")
		return {"__codex_error__": true}
	return data

func require_key(payload: Dictionary, key: String) -> Variant:
	if not payload.has(key):
		fail("missing key: %s" % key)
		return null
	return payload[key]

func escape_ini_string(value: String) -> String:
	return value.replace("\\", "\\\\").replace("\"", "\\\"")

func fail(message: String) -> void:
	printerr("[ERROR] %s" % message)
	quit(1)

